deploy s3

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -19,20 +19,27 @@ jobs:
         terraform_version: 1.9.5
 
     - name: Terraform Init
-      run: terraform init -chdir=./infra
+      run: |
+        cd infra
+        terraform init
 
     - name: Terraform Plan
-      run: terraform plan -chdir=./infra
+      run: |
+        cd infra
+        terraform plan
 
     - name: Terraform Apply
-      run: terraform apply -auto-approve -chdir=./infra
+      run: |
+        cd infra
+        terraform apply -auto-approve
 
     - name: Extract Terraform Outputs
       id: terraform_outputs
       run: |
+        cd infra
         echo "Extracting Terraform Outputs..."
-        S3_BUCKET=$(terraform output -raw s3_bucket_name -chdir=./infra | tr -d '\r' || echo "ERROR")
-        S3_WEBSITE_URL=$(terraform output -raw s3_website_url -chdir=./infra | tr -d '\r' || echo "ERROR")
+        S3_BUCKET=$(terraform output -raw s3_bucket_name | tr -d '\r' || echo "ERROR")
+        S3_WEBSITE_URL=$(terraform output -raw s3_website_url | tr -d '\r' || echo "ERROR")
         echo "S3_BUCKET=${S3_BUCKET}"
         echo "S3_WEBSITE_URL=${S3_WEBSITE_URL}"
         if [ "$S3_BUCKET" == "ERROR" ] || [ "$S3_WEBSITE_URL" == "ERROR" ]; then
