revisao de env

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -41,13 +41,23 @@ jobs:
         echo "Contents of s3_website_url.txt:"
         cat s3_website_url.txt
 
+    - name: Verify Files
+      run: |
+        echo "Verifying files..."
+        if [ -f ./infra/s3_bucket_name.txt ] && [ -f ./infra/s3_website_url.txt ]; then
+          echo "Files found."
+        else
+          echo "Error: Files not found."
+          exit 1
+        fi
+
     - name: Upload Terraform Outputs
       uses: actions/upload-artifact@v3
       with:
         name: terraform-outputs
         path: |
-          s3_bucket_name.txt
-          s3_website_url.txt
+          ./infra/s3_bucket_name.txt
+          ./infra/s3_website_url.txt
 
   deploy:
     runs-on: ubuntu-latest
@@ -82,7 +92,7 @@ jobs:
           echo "S3_BUCKET=${S3_BUCKET}" >> $GITHUB_ENV
           echo "S3_WEBSITE_URL=${S3_WEBSITE_URL}" >> $GITHUB_ENV
         else
-          echo "Erro: Arquivos de saída não encontrados."
+          echo "Error: Files not found."
           exit 1
         fi
         echo "S3_BUCKET=${S3_BUCKET}"
@@ -92,7 +102,7 @@ jobs:
       run: |
         echo "Deploying to S3..."
         if [ -z "$S3_BUCKET" ]; then
-          echo "Erro: Nome do bucket S3 não definido."
+          echo "Error: S3 bucket name not defined."
           exit 1
         fi
         aws s3 sync ./build s3://$S3_BUCKET --delete
