deploy to s3

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -35,8 +35,8 @@ jobs:
       working-directory: ./infra
       run: |
         echo "Extracting Terraform Outputs..."
-        S3_BUCKET=$(terraform output -raw s3_bucket_name || echo "ERROR")
-        S3_WEBSITE_URL=$(terraform output -raw s3_website_url || echo "ERROR")
+        S3_BUCKET=$(terraform output -raw s3_bucket_name | tr -d '\r' || echo "ERROR")
+        S3_WEBSITE_URL=$(terraform output -raw s3_website_url | tr -d '\r' || echo "ERROR")
 
         # Debugging output
         echo "S3_BUCKET=${S3_BUCKET}"
@@ -98,8 +98,8 @@ jobs:
       run: |
         echo "Setting environment variables..."
         if [ -f s3_bucket_name.txt ] && [ -f s3_website_url.txt ]; then
-          S3_BUCKET=$(cat s3_bucket_name.txt | tr -d '\n')
-          S3_WEBSITE_URL=$(cat s3_website_url.txt | tr -d '\n')
+          S3_BUCKET=$(cat s3_bucket_name.txt | tr -d '\r')
+          S3_WEBSITE_URL=$(cat s3_website_url.txt | tr -d '\r')
           echo "S3_BUCKET=${S3_BUCKET}" >> $GITHUB_ENV
           echo "S3_WEBSITE_URL=${S3_WEBSITE_URL}" >> $GITHUB_ENV
         else
