deploy s3

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -36,16 +36,16 @@ jobs:
       run: |
         echo "Extracting Terraform Outputs..."
 
-        # Capture Terraform output and handle potential errors
-        S3_BUCKET=$(terraform output -raw s3_bucket_name 2>&1 || echo "ERROR")
-        S3_WEBSITE_URL=$(terraform output -raw s3_website_url 2>&1 || echo "ERROR")
+        # Capture Terraform output
+        S3_BUCKET=$(terraform output -raw s3_bucket_name 2>/dev/null || echo "ERROR")
+        S3_WEBSITE_URL=$(terraform output -raw s3_website_url 2>/dev/null || echo "ERROR")
 
         # Print outputs for debugging
         echo "S3_BUCKET=${S3_BUCKET}"
         echo "S3_WEBSITE_URL=${S3_WEBSITE_URL}"
 
         # Check for errors and set environment variables
-        if [[ "$S3_BUCKET" == "ERROR" ]] || [[ "$S3_WEBSITE_URL" == "ERROR" ]]; then
+        if [ "$S3_BUCKET" == "ERROR" ] || [ "$S3_WEBSITE_URL" == "ERROR" ]; then
           echo "Error extracting Terraform outputs"
           exit 1
         fi
@@ -64,5 +64,5 @@ jobs:
         AWS_REGION: "sa-east-1"
         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-        S3_BUCKET: ${{ secrets.S3_BUCKET }}
-        S3_WEBSITE_URL: ${{ secrets.S3_WEBSITE_URL }}
+        S3_BUCKET: ${{ env.S3_BUCKET }}
+        S3_WEBSITE_URL: ${{ env.S3_WEBSITE_URL }}
