novo workflow v1.9.9.2

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -38,7 +38,13 @@ jobs:
         terraform output -json > terraform_outputs.json
         cat terraform_outputs.json
 
-        # Usando jq para extrair os valores
+        # Verificar se o arquivo foi criado e tem conteúdo
+        if [ ! -f terraform_outputs.json ] || [ ! -s terraform_outputs.json ]; then
+          echo "Error: terraform_outputs.json file is missing or empty."
+          exit 1
+        fi
+
+        # Usar jq para extrair os valores
         S3_BUCKET=$(jq -r '.s3_bucket_name.value' terraform_outputs.json)
         S3_WEBSITE_URL=$(jq -r '.s3_website_url.value' terraform_outputs.json)
 
