deploy to s3

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -35,8 +35,14 @@ jobs:
       working-directory: ./infra
       run: |
         echo "Extracting Terraform Outputs..."
-        echo "S3_BUCKET=$(terraform output -raw s3_bucket_name)" >> $GITHUB_ENV
-        echo "S3_WEBSITE_URL=$(terraform output -raw s3_website_url)" >> $GITHUB_ENV
+        S3_BUCKET=$(terraform output -raw s3_bucket_name || echo "ERROR")
+        S3_WEBSITE_URL=$(terraform output -raw s3_website_url || echo "ERROR")
+        if [ "$S3_BUCKET" == "ERROR" ] || [ "$S3_WEBSITE_URL" == "ERROR" ]; then
+          echo "Error extracting Terraform outputs"
+          exit 1
+        fi
+        echo "S3_BUCKET=${S3_BUCKET}" >> $GITHUB_ENV
+        echo "S3_WEBSITE_URL=${S3_WEBSITE_URL}" >> $GITHUB_ENV
 
   deploy:
     runs-on: ubuntu-latest
@@ -74,3 +80,5 @@ jobs:
         AWS_REGION: "sa-east-1"
         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+        S3_BUCKET: ${{ env.S3_BUCKET }}
+        S3_WEBSITE_URL: ${{ env.S3_WEBSITE_URL }}
