new version terraform

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -34,28 +34,31 @@ jobs:
       id: extract-outputs
       working-directory: ./infra
       run: |
-        terraform output -raw s3_bucket_name > s3_bucket_name.txt
-        terraform output -raw s3_website_url > s3_website_url.txt
+        terraform output s3_bucket_name > s3_bucket_name.txt
+        terraform output s3_website_url > s3_website_url.txt
         echo "Contents of s3_bucket_name.txt:"
         cat s3_bucket_name.txt
         echo "Contents of s3_website_url.txt:"
         cat s3_website_url.txt
 
-    - name: Set Environment Variables
-      id: set-env
+    - name: Verify Files
       run: |
-        echo "Setting environment variables..."
-        if [ -f s3_bucket_name.txt ] && [ -f s3_website_url.txt ]; then
-          S3_BUCKET=$(cat s3_bucket_name.txt | tr -d '\n')
-          S3_WEBSITE_URL=$(cat s3_website_url.txt | tr -d '\n')
-          echo "S3_BUCKET=${S3_BUCKET}" >> $GITHUB_ENV
-          echo "S3_WEBSITE_URL=${S3_WEBSITE_URL}" >> $GITHUB_ENV
+        echo "Verifying files..."
+        ls -l ./infra
+        if [ -f ./infra/s3_bucket_name.txt ] && [ -f ./infra/s3_website_url.txt ]; then
+          echo "Files found."
         else
-          echo "Erro: Arquivos de saída não encontrados."
+          echo "Error: Files not found."
           exit 1
         fi
-        echo "S3_BUCKET=${S3_BUCKET}"
-        echo "S3_WEBSITE_URL=${S3_WEBSITE_URL}"
+
+    - name: Upload Terraform Outputs
+      uses: actions/upload-artifact@v3
+      with:
+        name: terraform-outputs
+        path: |
+          ./infra/s3_bucket_name.txt
+          ./infra/s3_website_url.txt
 
   deploy:
     runs-on: ubuntu-latest
@@ -76,11 +79,31 @@ jobs:
     - name: Build site
       run: npm run build
 
+    - name: Download Terraform Outputs
+      uses: actions/download-artifact@v3
+      with:
+        name: terraform-outputs
+
+    - name: Set Environment Variables
+      run: |
+        echo "Setting environment variables..."
+        if [ -f s3_bucket_name.txt ] && [ -f s3_website_url.txt ]; then
+          S3_BUCKET=$(cat s3_bucket_name.txt | tr -d '\n')
+          S3_WEBSITE_URL=$(cat s3_website_url.txt | tr -d '\n')
+          echo "S3_BUCKET=${S3_BUCKET}" >> $GITHUB_ENV
+          echo "S3_WEBSITE_URL=${S3_WEBSITE_URL}" >> $GITHUB_ENV
+        else
+          echo "Error: Files not found."
+          exit 1
+        fi
+        echo "S3_BUCKET=${S3_BUCKET}"
+        echo "S3_WEBSITE_URL=${S3_WEBSITE_URL}"
+
     - name: Deploy to S3
       run: |
         echo "Deploying to S3..."
         if [ -z "$S3_BUCKET" ]; then
-          echo "Erro: Nome do bucket S3 não definido."
+          echo "Error: S3 bucket name not defined."
           exit 1
         fi
         aws s3 sync ./build s3://$S3_BUCKET --delete
